CREATE TABLE [dbo].[mapSolarSystems] (
    [regionID]        INT            NULL,
    [constellationID] INT            NULL,
    [solarSystemID]   INT            NOT NULL,
    [solarSystemName] NVARCHAR (100) NULL,
    [x]               FLOAT (53)     NULL,
    [y]               FLOAT (53)     NULL,
    [z]               FLOAT (53)     NULL,
    [xMin]            FLOAT (53)     NULL,
    [xMax]            FLOAT (53)     NULL,
    [yMin]            FLOAT (53)     NULL,
    [yMax]            FLOAT (53)     NULL,
    [zMin]            FLOAT (53)     NULL,
    [zMax]            FLOAT (53)     NULL,
    [luminosity]      FLOAT (53)     NULL,
    [border]          BIT            NULL,
    [fringe]          BIT            NULL,
    [corridor]        BIT            NULL,
    [hub]             BIT            NULL,
    [international]   BIT            NULL,
    [regional]        BIT            NULL,
    [constellation]   BIT            NULL,
    [security]        FLOAT (53)     NULL,
    [factionID]       INT            NULL,
    [radius]          FLOAT (53)     NULL,
    [sunTypeID]       INT            NULL,
    [securityClass]   VARCHAR (2)    NULL,
    CONSTRAINT [mapSolarSystems_PK] PRIMARY KEY CLUSTERED ([solarSystemID] ASC)
);

