CREATE TABLE [dbo].[dgmEffects] (
    [effectID]                       SMALLINT       NOT NULL,
    [effectName]                     VARCHAR (400)  COLLATE Latin1_General_CI_AI NULL,
    [effectCategory]                 SMALLINT       NULL,
    [preExpression]                  INT            NULL,
    [postExpression]                 INT            NULL,
    [description]                    VARCHAR (1000) NULL,
    [guid]                           VARCHAR (60)   NULL,
    [iconID]                         INT            NULL,
    [isOffensive]                    BIT            NULL,
    [isAssistance]                   BIT            NULL,
    [durationAttributeID]            SMALLINT       NULL,
    [trackingSpeedAttributeID]       SMALLINT       NULL,
    [dischargeAttributeID]           SMALLINT       NULL,
    [rangeAttributeID]               SMALLINT       NULL,
    [falloffAttributeID]             SMALLINT       NULL,
    [disallowAutoRepeat]             BIT            NULL,
    [published]                      BIT            NULL,
    [displayName]                    VARCHAR (100)  NULL,
    [isWarpSafe]                     BIT            NULL,
    [rangeChance]                    BIT            NULL,
    [electronicChance]               BIT            NULL,
    [propulsionChance]               BIT            NULL,
    [distribution]                   TINYINT        NULL,
    [sfxName]                        VARCHAR (20)   NULL,
    [npcUsageChanceAttributeID]      SMALLINT       NULL,
    [npcActivationChanceAttributeID] SMALLINT       NULL,
    [fittingUsageChanceAttributeID]  SMALLINT       NULL,
    [modifierInfo]                   VARCHAR (MAX)  NULL,
    CONSTRAINT [dgmEffects_PK] PRIMARY KEY CLUSTERED ([effectID] ASC)
);

