CREATE TABLE [dbo].[crpNPCCorporations] (
    [corporationID]      INT             NOT NULL,
    [size]               CHAR (1)        NULL,
    [extent]             CHAR (1)        NULL,
    [solarSystemID]      INT             NULL,
    [investorID1]        INT             NULL,
    [investorShares1]    TINYINT         NULL,
    [investorID2]        INT             NULL,
    [investorShares2]    TINYINT         NULL,
    [investorID3]        INT             NULL,
    [investorShares3]    TINYINT         NULL,
    [investorID4]        INT             NULL,
    [investorShares4]    TINYINT         NULL,
    [friendID]           INT             NULL,
    [enemyID]            INT             NULL,
    [publicShares]       BIGINT          NULL,
    [initialPrice]       INT             NULL,
    [minSecurity]        FLOAT (53)      NULL,
    [scattered]          BIT             NULL,
    [fringe]             TINYINT         NULL,
    [corridor]           TINYINT         NULL,
    [hub]                TINYINT         NULL,
    [border]             TINYINT         NULL,
    [factionID]          INT             NULL,
    [sizeFactor]         FLOAT (53)      NULL,
    [stationCount]       SMALLINT        NULL,
    [stationSystemCount] SMALLINT        NULL,
    [description]        NVARCHAR (4000) NULL,
    [iconID]             INT             NULL,
    CONSTRAINT [crpNPCCorporations_PK] PRIMARY KEY CLUSTERED ([corporationID] ASC)
);

